apiVersion : apps/v1
kind: Deployment
metadata:
  name: mavenexercise 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenexercise
  template:
    metadata:
      labels:
        app: mavenexercise
    spec:
      containers:
        - name: mavenexercise
          image: idoalon/maven_exercise:latest
          ports:
          - containerPort: 8080
