apiVersion : apps/v1
kind: Deployment
metadata:
  name: mavenexercise 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenexercise
  template:
    metadata:
      labels:
        app: mavenexercise
    spec:
      containers:
        - name: mavenexercise
          image: ors09/goapp
          ports:
          - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: mavenexercise-service
spec:
  selector:
    app: mavenexercise 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
    nodePort: 31110
