apiVersion : apps/v1
kind: Deployment
metadata:
  name: mavenexercise 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenexercise
  template:
    metadata:
      labels:
        app: mavenexercise
    spec:
      containers:
        - name: mavenexercise
          command: "java"
          args:
          - "-jar"
          - "target/my-app-1.0-SNAPSHOT.jar"
          - "--server.port=5555"
          image: idoalon/maven-exercise
          ports:
          - containerPort: 5555


---

apiVersion: v1
kind: Service
metadata:
  name: mavenexercise-service
spec:
  selector:
    app: mavenexercise 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 31110
